buildscript {
    repositories { google(); mavenCentral() }
    dependencies { classpath 'com.android.tools.build:gradle:9.4.0' }
}
allprojects {
    repositories {
        google()
        maven {
            url 'https://maven.aliyun.com/repository/public/'
            content { includeGroup 'org.hamcrest'; includeGroup 'junit' }
        }
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
tasks.register('clean', Delete) { delete rootProject.layout.buildDirectory }
