package com.tianma.xsmscode.data.db.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tianma.xsmscode.data.db.entity.AppInfo;
import com.tianma.xsmscode.data.db.entity.SmsCodeRule;
import com.tianma.xsmscode.data.db.entity.SmsMsg;

import com.tianma.xsmscode.data.db.entity.AppInfoDao;
import com.tianma.xsmscode.data.db.entity.SmsCodeRuleDao;
import com.tianma.xsmscode.data.db.entity.SmsMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appInfoDaoConfig;
    private final DaoConfig smsCodeRuleDaoConfig;
    private final DaoConfig smsMsgDaoConfig;

    private final AppInfoDao appInfoDao;
    private final SmsCodeRuleDao smsCodeRuleDao;
    private final SmsMsgDao smsMsgDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appInfoDaoConfig = daoConfigMap.get(AppInfoDao.class).clone();
        appInfoDaoConfig.initIdentityScope(type);

        smsCodeRuleDaoConfig = daoConfigMap.get(SmsCodeRuleDao.class).clone();
        smsCodeRuleDaoConfig.initIdentityScope(type);

        smsMsgDaoConfig = daoConfigMap.get(SmsMsgDao.class).clone();
        smsMsgDaoConfig.initIdentityScope(type);

        appInfoDao = new AppInfoDao(appInfoDaoConfig, this);
        smsCodeRuleDao = new SmsCodeRuleDao(smsCodeRuleDaoConfig, this);
        smsMsgDao = new SmsMsgDao(smsMsgDaoConfig, this);

        registerDao(AppInfo.class, appInfoDao);
        registerDao(SmsCodeRule.class, smsCodeRuleDao);
        registerDao(SmsMsg.class, smsMsgDao);
    }
    
    public void clear() {
        appInfoDaoConfig.clearIdentityScope();
        smsCodeRuleDaoConfig.clearIdentityScope();
        smsMsgDaoConfig.clearIdentityScope();
    }

    public AppInfoDao getAppInfoDao() {
        return appInfoDao;
    }

    public SmsCodeRuleDao getSmsCodeRuleDao() {
        return smsCodeRuleDao;
    }

    public SmsMsgDao getSmsMsgDao() {
        return smsMsgDao;
    }

}
