package com.tianma.xsmscode.data.db.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SMS_CODE_RULE".
*/
public class SmsCodeRuleDao extends AbstractDao<SmsCodeRule, Long> {

    public static final String TABLENAME = "SMS_CODE_RULE";

    /**
     * Properties of entity SmsCodeRule.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Company = new Property(1, String.class, "company", false, "COMPANY");
        public final static Property CodeKeyword = new Property(2, String.class, "codeKeyword", false, "CODE_KEYWORD");
        public final static Property CodeRegex = new Property(3, String.class, "codeRegex", false, "CODE_REGEX");
    }


    public SmsCodeRuleDao(DaoConfig config) {
        super(config);
    }
    
    public SmsCodeRuleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SMS_CODE_RULE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"COMPANY\" TEXT," + // 1: company
                "\"CODE_KEYWORD\" TEXT NOT NULL ," + // 2: codeKeyword
                "\"CODE_REGEX\" TEXT NOT NULL );"); // 3: codeRegex
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_SMS_CODE_RULE_COMPANY_CODE_KEYWORD_CODE_REGEX ON \"SMS_CODE_RULE\"" +
                " (\"COMPANY\" ASC,\"CODE_KEYWORD\" ASC,\"CODE_REGEX\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SMS_CODE_RULE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SmsCodeRule entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String company = entity.getCompany();
        if (company != null) {
            stmt.bindString(2, company);
        }
        stmt.bindString(3, entity.getCodeKeyword());
        stmt.bindString(4, entity.getCodeRegex());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SmsCodeRule entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String company = entity.getCompany();
        if (company != null) {
            stmt.bindString(2, company);
        }
        stmt.bindString(3, entity.getCodeKeyword());
        stmt.bindString(4, entity.getCodeRegex());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SmsCodeRule readEntity(Cursor cursor, int offset) {
        SmsCodeRule entity = new SmsCodeRule( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // company
            cursor.getString(offset + 2), // codeKeyword
            cursor.getString(offset + 3) // codeRegex
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SmsCodeRule entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCompany(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCodeKeyword(cursor.getString(offset + 2));
        entity.setCodeRegex(cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SmsCodeRule entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SmsCodeRule entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SmsCodeRule entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
